coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
ignore:
  - apps/shoppingmanager/database/generated
  - apps/shoppingmanager/database/jooqgen